"""add_field_drop_tables

Revision ID: 0dae98b2cb89
Revises: 93173a4f92a4
Create Date: 2026-03-21 00:39:47.521421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dae98b2cb89'
down_revision: Union[str, None] = '93173a4f92a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('field_supply_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_supply_requests', schema=None) as batch_op:
        batch_op.create_index('ix_field_supply_requests_created_at', ['created_at'], unique=False)

    op.create_table('field_dispatch_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('position_name', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('eta_min', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['field_positions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['field_supply_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_dispatch_logs', schema=None) as batch_op:
        batch_op.create_index('ix_field_dispatch_logs_created_at', ['created_at'], unique=False)

    op.create_table('field_inventory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['field_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_inventory_items', schema=None) as batch_op:
        batch_op.create_index('ix_field_inventory_items_item_name', ['item_name'], unique=False)
        batch_op.create_index('ix_field_inventory_items_position_item', ['position_id', 'item_name'], unique=False)

    op.create_table('field_supply_needs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['field_supply_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('unit')

    op.drop_table('field_supply_needs')
    with op.batch_alter_table('field_inventory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_field_inventory_items_position_item')
        batch_op.drop_index('ix_field_inventory_items_item_name')

    op.drop_table('field_inventory_items')
    with op.batch_alter_table('field_dispatch_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_field_dispatch_logs_created_at')

    op.drop_table('field_dispatch_logs')
    with op.batch_alter_table('field_supply_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_field_supply_requests_created_at')

    op.drop_table('field_supply_requests')
    op.drop_table('field_positions')
    # ### end Alembic commands ###
