"""Add personnel records tables

Revision ID: 35c95be7bfc5
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 04:58:44.895760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c95be7bfc5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create service_members table
    op.create_table('service_members',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_number', sa.String(), nullable=True),
        sa.Column('social_security', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('middle_name', sa.String(), nullable=True),
        sa.Column('date_of_birth', sa.DateTime(), nullable=True),
        sa.Column('place_of_birth', sa.String(), nullable=True),
        sa.Column('citizenship', sa.String(), nullable=True),
        sa.Column('rank', sa.String(), nullable=True),
        sa.Column('specialty', sa.String(), nullable=True),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('position', sa.String(), nullable=True),
        sa.Column('enlistment_date', sa.DateTime(), nullable=True),
        sa.Column('service_start_date', sa.DateTime(), nullable=True),
        sa.Column('contract_end_date', sa.DateTime(), nullable=True),
        sa.Column('years_of_service', sa.Float(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('emergency_contact', sa.JSON(), nullable=True),
        sa.Column('blood_type', sa.String(), nullable=True),
        sa.Column('allergies', sa.Text(), nullable=True),
        sa.Column('medical_conditions', sa.Text(), nullable=True),
        sa.Column('medications', sa.Text(), nullable=True),
        sa.Column('last_physical_date', sa.DateTime(), nullable=True),
        sa.Column('deployments', sa.JSON(), nullable=True),
        sa.Column('combat_experience', sa.Boolean(), nullable=True),
        sa.Column('awards', sa.JSON(), nullable=True),
        sa.Column('qualifications', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('is_deployed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('service_number'),
        sa.UniqueConstraint('social_security')
    )
    op.create_index(op.f('ix_service_members_service_number'), 'service_members', ['service_number'], unique=True)
    op.create_index(op.f('ix_service_members_social_security'), 'service_members', ['social_security'], unique=True)
    
    # Create personnel_records table
    op.create_table('personnel_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_member_id', sa.String(), nullable=False),
        sa.Column('record_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('effective_date', sa.DateTime(), nullable=True),
        sa.Column('recorded_date', sa.DateTime(), nullable=True),
        sa.Column('document_references', sa.JSON(), nullable=True),
        sa.Column('recorded_by', sa.String(), nullable=True),
        sa.Column('authorizing_official', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create medical_records table
    op.create_table('medical_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_member_id', sa.String(), nullable=False),
        sa.Column('case_id', sa.String(), nullable=True),
        sa.Column('record_type', sa.String(), nullable=False),
        sa.Column('diagnosis', sa.String(), nullable=True),
        sa.Column('diagnosis_code', sa.String(), nullable=True),
        sa.Column('treatment', sa.Text(), nullable=True),
        sa.Column('medications', sa.Text(), nullable=True),
        sa.Column('procedures', sa.Text(), nullable=True),
        sa.Column('provider_name', sa.String(), nullable=True),
        sa.Column('provider_type', sa.String(), nullable=True),
        sa.Column('facility', sa.String(), nullable=True),
        sa.Column('encounter_date', sa.DateTime(), nullable=True),
        sa.Column('discharge_date', sa.DateTime(), nullable=True),
        sa.Column('outcome', sa.String(), nullable=True),
        sa.Column('return_to_duty_date', sa.DateTime(), nullable=True),
        sa.Column('limited_duty', sa.Boolean(), nullable=True),
        sa.Column('limited_duty_end_date', sa.DateTime(), nullable=True),
        sa.Column('injury_type', sa.String(), nullable=True),
        sa.Column('injury_mechanism', sa.String(), nullable=True),
        sa.Column('injury_severity', sa.String(), nullable=True),
        sa.Column('documents', sa.JSON(), nullable=True),
        sa.Column('recorded_by', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id']),
        sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create deployment_records table
    op.create_table('deployment_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_member_id', sa.String(), nullable=False),
        sa.Column('operation_name', sa.String(), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('theater', sa.String(), nullable=True),
        sa.Column('unit_command', sa.String(), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('duration_days', sa.Integer(), nullable=True),
        sa.Column('mission_type', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('events', sa.JSON(), nullable=True),
        sa.Column('injuries', sa.JSON(), nullable=True),
        sa.Column('awards', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create personnel_documents table
    op.create_table('personnel_documents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_member_id', sa.String(), nullable=False),
        sa.Column('document_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('mime_type', sa.String(), nullable=True),
        sa.Column('checksum', sa.String(), nullable=True),
        sa.Column('document_date', sa.DateTime(), nullable=True),
        sa.Column('effective_date', sa.DateTime(), nullable=True),
        sa.Column('expiry_date', sa.DateTime(), nullable=True),
        sa.Column('issuing_authority', sa.String(), nullable=True),
        sa.Column('authorizing_official', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('is_classified', sa.Boolean(), nullable=True),
        sa.Column('classification_level', sa.String(), nullable=True),
        sa.Column('uploaded_by', sa.String(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # SQLite doesn't support ALTER COLUMN, so we'll skip the default removal
    # op.alter_column('cases', 'evac_status',
    #                existing_type=sa.VARCHAR(),
    #                server_default=None,
    #                existing_nullable=True)
    # op.alter_column('sync_queue', 'status',
    #                existing_type=sa.VARCHAR(),
    #                server_default=None,
    #                existing_nullable=False)
    # op.alter_column('sync_queue', 'retries',
    #                existing_type=sa.INTEGER(),
    #                server_default=None,
    #                existing_nullable=False)
    # op.alter_column('users', 'role',
    #                existing_type=sa.VARCHAR(),
    #                server_default=None,
    #                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN with defaults
    op.drop_table('personnel_documents')
    op.drop_table('deployment_records')
    op.drop_table('medical_records')
    op.drop_table('personnel_records')
    op.drop_table('service_members')
    # ### end Alembic commands ###
