"""add_notes_to_case

Revision ID: 73769e30d780
Revises: a05ce5293cc6
Create Date: 2026-03-17 20:56:47.906548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73769e30d780'
down_revision: Union[str, None] = 'a05ce5293cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'notes')
    # ### end Alembic commands ###
