"""Normalize tables

Revision ID: 93173a4f92a4
Revises: 35c95be7bfc5
Create Date: 2026-03-18 20:39:11.433142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '93173a4f92a4'
down_revision: Union[str, None] = '35c95be7bfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evacuation_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('evacuation_priority', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('nine_line_sent', sa.Boolean(), nullable=True),
    sa.Column('handoff_to', sa.String(), nullable=True),
    sa.Column('mist_summary', sa.String(), nullable=True),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evacuation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evacuation_records_case_id'), ['case_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_case_id'), ['case_id'], unique=False)

    op.create_table('injuries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('body_region', sa.String(), nullable=False),
    sa.Column('injury_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('laterality', sa.String(), nullable=True),
    sa.Column('mechanism', sa.String(), nullable=True),
    sa.Column('penetrating', sa.Boolean(), nullable=True),
    sa.Column('view', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_case_id'), ['case_id'], unique=False)

    op.create_table('march_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('m_massive_bleeding', sa.Boolean(), nullable=True),
    sa.Column('m_tourniquets_applied', sa.Integer(), nullable=True),
    sa.Column('m_hemostatic_agent', sa.Boolean(), nullable=True),
    sa.Column('m_notes', sa.Text(), nullable=True),
    sa.Column('a_airway_open', sa.Boolean(), nullable=True),
    sa.Column('a_airway_intervention', sa.String(), nullable=True),
    sa.Column('a_notes', sa.Text(), nullable=True),
    sa.Column('r_breathing_rate', sa.Integer(), nullable=True),
    sa.Column('r_chest_seal_applied', sa.Boolean(), nullable=True),
    sa.Column('r_needle_d_performed', sa.Boolean(), nullable=True),
    sa.Column('r_chest_tube', sa.Boolean(), nullable=True),
    sa.Column('r_notes', sa.Text(), nullable=True),
    sa.Column('c_radial_pulse', sa.String(), nullable=True),
    sa.Column('c_capillary_refill_time', sa.String(), nullable=True),
    sa.Column('c_pelvic_binder', sa.Boolean(), nullable=True),
    sa.Column('c_tibial_io', sa.Boolean(), nullable=True),
    sa.Column('c_sternal_io', sa.Boolean(), nullable=True),
    sa.Column('c_iv_access', sa.Boolean(), nullable=True),
    sa.Column('c_notes', sa.Text(), nullable=True),
    sa.Column('h_hypothermia_prevented', sa.Boolean(), nullable=True),
    sa.Column('h_blanket_applied', sa.Boolean(), nullable=True),
    sa.Column('h_active_warming', sa.Boolean(), nullable=True),
    sa.Column('h_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('march_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_march_assessments_case_id'), ['case_id'], unique=False)

    op.create_table('medication_administrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('medication_code', sa.String(), nullable=False),
    sa.Column('dose_value', sa.String(), nullable=True),
    sa.Column('dose_unit_code', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('time_administered', sa.DateTime(), nullable=True),
    sa.Column('indication', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administrations_case_id'), ['case_id'], unique=False)

    op.create_table('procedures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('procedure_code', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('laterality', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('success_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedures_case_id'), ['case_id'], unique=False)

    op.create_table('vitals_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('spo2_percent', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('gcs_total', sa.Integer(), nullable=True),
    sa.Column('avpu', sa.String(), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vitals_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vitals_observations_case_id'), ['case_id'], unique=False)

    op.drop_table('case_medication_administrations')
    op.drop_table('case_injuries')
    op.drop_table('deployment_records')
    op.drop_table('case_observations')
    op.drop_table('case_handoffs')
    op.drop_table('medical_records')
    op.drop_table('personnel_records')
    op.drop_table('personnel_documents')
    with op.batch_alter_table('service_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_members_service_number'))
        batch_op.drop_index(batch_op.f('ix_service_members_social_security'))

    op.drop_table('service_members')
    op.drop_table('case_procedures')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_values', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_values', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('client_ip', sa.String(), nullable=True))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approx_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('geo_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('geo_lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('case_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tourniquet_applied', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tourniquet_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sync_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('server_version', sa.Integer(), nullable=True))
        batch_op.alter_column('allergies',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('mechanism_of_injury',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('airway')
        batch_op.drop_column('tourniquets_json')
        batch_op.drop_column('exposure')
        batch_op.drop_column('vitals_json')
        batch_op.drop_column('evac_time')
        batch_op.drop_column('disability')
        batch_op.drop_column('medications_json')
        batch_op.drop_column('evac_status')
        batch_op.drop_column('treatments_json')
        batch_op.drop_column('circulation')
        batch_op.drop_column('injuries_json')
        batch_op.drop_column('breathing')
        batch_op.drop_column('evac_dest')
        batch_op.drop_column('body_injuries_json')

    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'medic'"),
               existing_nullable=False)

    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.alter_column('retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'"),
               existing_nullable=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_injuries_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('evac_dest', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('breathing', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('injuries_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('circulation', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('treatments_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('evac_status', sa.VARCHAR(), server_default=sa.text("'очікує'"), nullable=True))
        batch_op.add_column(sa.Column('medications_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('evac_time', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('vitals_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('exposure', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tourniquets_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('airway', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('mechanism_of_injury',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('allergies',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('server_version')
        batch_op.drop_column('sync_state')
        batch_op.drop_column('tourniquet_time')
        batch_op.drop_column('tourniquet_applied')
        batch_op.drop_column('case_status')
        batch_op.drop_column('geo_lon')
        batch_op.drop_column('geo_lat')
        batch_op.drop_column('approx_age')
        batch_op.drop_column('sex')
        batch_op.drop_column('case_number')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('client_ip')
        batch_op.drop_column('device_id')
        batch_op.drop_column('new_values')
        batch_op.drop_column('old_values')

    op.create_table('personnel_documents',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('service_member_id', sa.VARCHAR(), nullable=False),
    sa.Column('document_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(), nullable=True),
    sa.Column('document_date', sa.DATETIME(), nullable=True),
    sa.Column('effective_date', sa.DATETIME(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('issuing_authority', sa.VARCHAR(), nullable=True),
    sa.Column('authorizing_official', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('is_classified', sa.BOOLEAN(), nullable=True),
    sa.Column('classification_level', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_procedures',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('procedure_code', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_members',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('service_number', sa.VARCHAR(), nullable=True),
    sa.Column('social_security', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=True),
    sa.Column('place_of_birth', sa.VARCHAR(), nullable=True),
    sa.Column('citizenship', sa.VARCHAR(), nullable=True),
    sa.Column('rank', sa.VARCHAR(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('enlistment_date', sa.DATETIME(), nullable=True),
    sa.Column('service_start_date', sa.DATETIME(), nullable=True),
    sa.Column('contract_end_date', sa.DATETIME(), nullable=True),
    sa.Column('years_of_service', sa.FLOAT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('emergency_contact', sqlite.JSON(), nullable=True),
    sa.Column('blood_type', sa.VARCHAR(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('medical_conditions', sa.TEXT(), nullable=True),
    sa.Column('medications', sa.TEXT(), nullable=True),
    sa.Column('last_physical_date', sa.DATETIME(), nullable=True),
    sa.Column('deployments', sqlite.JSON(), nullable=True),
    sa.Column('combat_experience', sa.BOOLEAN(), nullable=True),
    sa.Column('awards', sqlite.JSON(), nullable=True),
    sa.Column('qualifications', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('is_deployed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_number'),
    sa.UniqueConstraint('social_security')
    )
    with op.batch_alter_table('service_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_members_social_security'), ['social_security'], unique=1)
        batch_op.create_index(batch_op.f('ix_service_members_service_number'), ['service_number'], unique=1)

    op.create_table('personnel_records',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('service_member_id', sa.VARCHAR(), nullable=False),
    sa.Column('record_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('effective_date', sa.DATETIME(), nullable=True),
    sa.Column('recorded_date', sa.DATETIME(), nullable=True),
    sa.Column('document_references', sqlite.JSON(), nullable=True),
    sa.Column('recorded_by', sa.VARCHAR(), nullable=True),
    sa.Column('authorizing_official', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('service_member_id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=True),
    sa.Column('record_type', sa.VARCHAR(), nullable=False),
    sa.Column('diagnosis', sa.VARCHAR(), nullable=True),
    sa.Column('diagnosis_code', sa.VARCHAR(), nullable=True),
    sa.Column('treatment', sa.TEXT(), nullable=True),
    sa.Column('medications', sa.TEXT(), nullable=True),
    sa.Column('procedures', sa.TEXT(), nullable=True),
    sa.Column('provider_name', sa.VARCHAR(), nullable=True),
    sa.Column('provider_type', sa.VARCHAR(), nullable=True),
    sa.Column('facility', sa.VARCHAR(), nullable=True),
    sa.Column('encounter_date', sa.DATETIME(), nullable=True),
    sa.Column('discharge_date', sa.DATETIME(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(), nullable=True),
    sa.Column('return_to_duty_date', sa.DATETIME(), nullable=True),
    sa.Column('limited_duty', sa.BOOLEAN(), nullable=True),
    sa.Column('limited_duty_end_date', sa.DATETIME(), nullable=True),
    sa.Column('injury_type', sa.VARCHAR(), nullable=True),
    sa.Column('injury_mechanism', sa.VARCHAR(), nullable=True),
    sa.Column('injury_severity', sa.VARCHAR(), nullable=True),
    sa.Column('documents', sqlite.JSON(), nullable=True),
    sa.Column('recorded_by', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_handoffs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('mist_summary', sa.TEXT(), nullable=True),
    sa.Column('operator_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_observations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('observation_type', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_records',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('service_member_id', sa.VARCHAR(), nullable=False),
    sa.Column('operation_name', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('theater', sa.VARCHAR(), nullable=True),
    sa.Column('unit_command', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('duration_days', sa.INTEGER(), nullable=True),
    sa.Column('mission_type', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('events', sqlite.JSON(), nullable=True),
    sa.Column('injuries', sqlite.JSON(), nullable=True),
    sa.Column('awards', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['service_member_id'], ['service_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_injuries',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('body_part_code', sa.VARCHAR(), nullable=True),
    sa.Column('injury_type_code', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_medication_administrations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('medication_code', sa.VARCHAR(), nullable=True),
    sa.Column('dose_value', sa.VARCHAR(), nullable=True),
    sa.Column('dose_unit_code', sa.VARCHAR(), nullable=True),
    sa.Column('time_administered', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vitals_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitals_observations_case_id'))

    op.drop_table('vitals_observations')
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedures_case_id'))

    op.drop_table('procedures')
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administrations_case_id'))

    op.drop_table('medication_administrations')
    with op.batch_alter_table('march_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_march_assessments_case_id'))

    op.drop_table('march_assessments')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_case_id'))

    op.drop_table('injuries')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_case_id'))

    op.drop_table('events')
    with op.batch_alter_table('evacuation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evacuation_records_case_id'))

    op.drop_table('evacuation_records')
    # ### end Alembic commands ###
